pub(crate) const SECOND_NANOSECONDS: u64 = 1000000000;
pub(crate) const MINUTE_NANOSECONDS: u64 = 60 * SECOND_NANOSECONDS;
pub(crate) const HOUR_NANOSECONDS: u64 = 60 * MINUTE_NANOSECONDS;
pub(crate) const DAY_NANOSECONDS: u64 = 24 * HOUR_NANOSECONDS;
